/* FIVES offline worker — GENERATED by fives/build-html.mjs. Do not edit.
   Scope comes from where this file sits, which is the root of a site that is
   nothing but Fives. Nothing else shares the origin. */
const CACHE = "fives-1e31d3eb";
const PRECACHE = [
  "./",
  "./fives.webmanifest",
  "./fives-icon-180.png",
  "./fives-icon-192.png",
  "./fives-icon-512.png"
];

self.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(PRECACHE))
      /* One missing file must not wedge the install and leave the player
         with no worker at all. A partial cache still beats none. */
      .catch(() => {})
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET") return;
  if (new URL(req.url).origin !== self.location.origin) return;

  e.respondWith(
    fetch(req)
      .then((res) => {
        /* Only bank real answers. Caching a 404 or an opaque error would
           mean serving that error forever once the signal goes. */
        if (res && res.ok && res.type === "basic") {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
        }
        return res;
      })
      .catch(() => caches.match(req).then((hit) => hit || Response.error()))
  );
});
